---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2022.

# Install Ansible 2.10 in a system virtualenv

- name: Install Ansible 2.10 from PyPI
  hosts: all

  tasks:
    - name: Install the Waco Python role and its dependencies
      include_tasks:
        file: load-roles.yml
      vars:
        role: waco_org.waco_python

    - name: Install Ansible in a virtualenv 
      include_role:
        name: waco_org.waco_python
      vars:
        - wapy_source_versions: []
        - wapy_has_ansible: true
