#!/bin/bash

# Workstation as Code
# Copyright Nicola Musatti 2020.

# waco-provision - performs Waco provisioning.
# Run by the waco user

pushd $(dirname "$0")

rm -rf roles
mkdir roles
if [[ $(ansible --version) =~ .*2\.9\..* ]]; then
    ansible-playbook -i hosts -l local ansible-workaround.yml
    source /opt/sysvenv-*/ansible/bin/activate
fi

ansible-playbook -i hosts -l local waco-provision.yml

popd
