---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2022.

- name: Perform Waco provisioning
  hosts: all
  vars_files:
    - settings/master.yml

  tasks:
    - name: Install the Waco master role and its dependencies
      include_tasks:
        file: load-roles.yml
      vars:
        role: waco_org.waco_master

    - name: Install optional Waco roles and their dependencies
      include_tasks:
        file: load-roles.yml
      loop: "{{ roles | dict2items }}"
      vars:
        role: "{{ item.key }}"
        roles:
          waco_org.waco_python: "{{ waco_has_python }}"
      when: item.value

    - name: Provision the system
      include_role:
        name: waco_org.waco_master
